name: Build & Push Docker image (GHCR)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "release-*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  MINIMAL_IMAGE_NAME: ${{ github.repository_owner }}/archlinuxarm-basic
  ALARM_IMAGE_NAME: ${{ github.repository_owner }}/archlinuxarm
  PLATFORMS: linux/arm64
  MINIMAL_DOCKERFILE: dockerfiles/Dockerfile.base
  ALARM_DOCKERFILE: dockerfiles/Dockerfile.aarch64
  TARGET: archarm
  ALARM_TARGET: builder

jobs:
  build:
    name: Build${{ github.event_name == 'pull_request' && ' (no push)' || '' }}
    runs-on: ubuntu-latest

    concurrency:
      group: docker-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-compiling images)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive image name
        id: img
        run: |
          echo "MINIMAL_IMAGE=${{ env.REGISTRY }}/${{ env.MINIMAL_IMAGE_NAME }}" >> $GITHUB_OUTPUT
          echo "ALARM_IMAGE=${{ env.REGISTRY }}/${{ env.ALARM_IMAGE_NAME }}" >> $GITHUB_OUTPUT

      - name: Extract Docker metadata (tags, labels)
        id: meta-minimal
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.img.outputs.MINIMAL_IMAGE }}
          # Tag strategy:
          # - main branch -> :latest and :sha
          # - tags like v1.2.3 -> :1.2.3 and :1.2 and :1
          # - PRs -> :pr-<num>-<sha>
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag

      - name: Extract Docker metadata (tags, labels)
        id: meta-alarm
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.img.outputs.ALARM_IMAGE }}
          # Tag strategy:
          # - main branch -> :latest and :sha
          # - tags like v1.2.3 -> :1.2.3 and :1.2 and :1
          # - PRs -> :pr-<num>-<sha>
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag

      - name: Build minimal (and push when not a PR)
        id: buildx
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.MINIMAL_DOCKERFILE }}
          target: ${{ env.TARGET }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-minimal.outputs.tags }}      # mirrors: -t $(IMAGE):minimal-aarch64 (+ semver / sha variants)
          labels: ${{ steps.meta-minimal.outputs.labels }}
          # Your local command used --load; in CI we push instead. (--load is single-arch only and not suited for multi-arch CI.)
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false

      - name: Build ArchLinuxARM (and push when not a PR)
        id: buildx-alarm
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.ALARM_DOCKERFILE }}
          target: ${{ env.ALARM_TARGET }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-alarm.outputs.tags }}      # mirrors: -t $(IMAGE):minimal-aarch64 (+ semver / sha variants)
          labels: ${{ steps.meta-alarm.outputs.labels }}
          # Your local command used --load; in CI we push instead. (--load is single-arch only and not suited for multi-arch CI.)
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
